// Base de dados de aeroportos IATA - 247 aeroportos
const AEROPORTOS_IATA = [
    {"codigo": "GRU", "nome": "São Paulo", "aeroporto": "Guarulhos", "pais": "Brasil"},
    {"codigo": "CGH", "nome": "São Paulo", "aeroporto": "Congonhas", "pais": "Brasil"},
    {"codigo": "VCP", "nome": "Campinas", "aeroporto": "Viracopos", "pais": "Brasil"},
    {"codigo": "GIG", "nome": "Rio de Janeiro", "aeroporto": "Galeão", "pais": "Brasil"},
    {"codigo": "SDU", "nome": "Rio de Janeiro", "aeroporto": "Santos Dumont", "pais": "Brasil"},
    {"codigo": "BSB", "nome": "Brasília", "aeroporto": "Presidente Juscelino Kubitschek", "pais": "Brasil"},
    {"codigo": "CNF", "nome": "Belo Horizonte", "aeroporto": "Confins", "pais": "Brasil"},
    {"codigo": "PLU", "nome": "Belo Horizonte", "aeroporto": "Pampulha", "pais": "Brasil"},
    {"codigo": "SSA", "nome": "Salvador", "aeroporto": "Deputado Luís Eduardo Magalhães", "pais": "Brasil"},
    {"codigo": "REC", "nome": "Recife", "aeroporto": "Guararapes", "pais": "Brasil"},
    {"codigo": "FOR", "nome": "Fortaleza", "aeroporto": "Pinto Martins", "pais": "Brasil"},
    {"codigo": "POA", "nome": "Porto Alegre", "aeroporto": "Salgado Filho", "pais": "Brasil"},
    {"codigo": "CWB", "nome": "Curitiba", "aeroporto": "Afonso Pena", "pais": "Brasil"},
    {"codigo": "FLN", "nome": "Florianópolis", "aeroporto": "Hercílio Luz", "pais": "Brasil"},
    {"codigo": "MAO", "nome": "Manaus", "aeroporto": "Eduardo Gomes", "pais": "Brasil"},
    {"codigo": "BEL", "nome": "Belém", "aeroporto": "Val de Cans", "pais": "Brasil"},
    {"codigo": "NAT", "nome": "Natal", "aeroporto": "Augusto Severo", "pais": "Brasil"},
    {"codigo": "MCZ", "nome": "Maceió", "aeroporto": "Zumbi dos Palmares", "pais": "Brasil"},
    {"codigo": "THE", "nome": "Teresina", "aeroporto": "Senador Petrônio Portella", "pais": "Brasil"},
    {"codigo": "JPA", "nome": "João Pessoa", "aeroporto": "Presidente Castro Pinto", "pais": "Brasil"},
    {"codigo": "AJU", "nome": "Aracaju", "aeroporto": "Santa Maria", "pais": "Brasil"},
    {"codigo": "VIX", "nome": "Vitória", "aeroporto": "Eurico de Aguiar Salles", "pais": "Brasil"},
    {"codigo": "CGB", "nome": "Cuiabá", "aeroporto": "Marechal Rondon", "pais": "Brasil"},
    {"codigo": "GYN", "nome": "Goiânia", "aeroporto": "Santa Genoveva", "pais": "Brasil"},
    {"codigo": "BPS", "nome": "Porto Seguro", "aeroporto": "Porto Seguro", "pais": "Brasil"},
    {"codigo": "IOS", "nome": "Ilhéus", "aeroporto": "Jorge Amado", "pais": "Brasil"},
    {"codigo": "VDC", "nome": "Vitória da Conquista", "aeroporto": "Glauber Rocha", "pais": "Brasil"},
    {"codigo": "FEN", "nome": "Fernando de Noronha", "aeroporto": "Fernando de Noronha", "pais": "Brasil"},
    {"codigo": "IGU", "nome": "Foz do Iguaçu", "aeroporto": "Cataratas", "pais": "Brasil"},
    {"codigo": "NVT", "nome": "Navegantes", "aeroporto": "Ministro Victor Konder", "pais": "Brasil"},
    {"codigo": "JOI", "nome": "Joinville", "aeroporto": "Lauro Carneiro de Loyola", "pais": "Brasil"},
    {"codigo": "UDI", "nome": "Uberlândia", "aeroporto": "Ten. Cel. Aviador César Bombonato", "pais": "Brasil"},
    {"codigo": "MGF", "nome": "Maringá", "aeroporto": "Regional de Maringá", "pais": "Brasil"},
    {"codigo": "LDB", "nome": "Londrina", "aeroporto": "Governador José Richa", "pais": "Brasil"},
    {"codigo": "PFB", "nome": "Passo Fundo", "aeroporto": "Lauro Kurtz", "pais": "Brasil"},
    {"codigo": "CXJ", "nome": "Caxias do Sul", "aeroporto": "Hugo Cantergiani", "pais": "Brasil"},
    {"codigo": "PPB", "nome": "Presidente Prudente", "aeroporto": "Adhemar de Barros", "pais": "Brasil"},
    {"codigo": "RAO", "nome": "Ribeirão Preto", "aeroporto": "Leite Lopes", "pais": "Brasil"},
    {"codigo": "SJK", "nome": "São José dos Campos", "aeroporto": "Professor Urbano Ernesto Stumpf", "pais": "Brasil"},
    {"codigo": "SOD", "nome": "Sorocaba", "aeroporto": "Bertram Luiz Leupolz", "pais": "Brasil"},
    {"codigo": "AQA", "nome": "Araraquara", "aeroporto": "Bartolomeu de Gusmão", "pais": "Brasil"},
    {"codigo": "JDO", "nome": "Juazeiro do Norte", "aeroporto": "Orlando Bezerra de Menezes", "pais": "Brasil"},
    {"codigo": "PNZ", "nome": "Petrolina", "aeroporto": "Senador Nilo Coelho", "pais": "Brasil"},
    {"codigo": "CPV", "nome": "Campina Grande", "aeroporto": "Presidente João Suassuna", "pais": "Brasil"},
    {"codigo": "IMP", "nome": "Imperatriz", "aeroporto": "Prefeito Renato Moreira", "pais": "Brasil"},
    {"codigo": "SLZ", "nome": "São Luís", "aeroporto": "Marechal Cunha Machado", "pais": "Brasil"},
    {"codigo": "PVH", "nome": "Porto Velho", "aeroporto": "Governador Jorge Teixeira", "pais": "Brasil"},
    {"codigo": "RBR", "nome": "Rio Branco", "aeroporto": "Plácido de Castro", "pais": "Brasil"},
    {"codigo": "BVB", "nome": "Boa Vista", "aeroporto": "Atlas Brasil Cantanhede", "pais": "Brasil"},
    {"codigo": "MCP", "nome": "Macapá", "aeroporto": "Alberto Alcolumbre", "pais": "Brasil"},
    {"codigo": "PBM", "nome": "Palmas", "aeroporto": "Brigadeiro Lysias Rodrigues", "pais": "Brasil"},
    {"codigo": "CZS", "nome": "Cruzeiro do Sul", "aeroporto": "Cruzeiro do Sul", "pais": "Brasil"},
    {"codigo": "TMT", "nome": "Trombetas", "aeroporto": "Trombetas", "pais": "Brasil"},
    {"codigo": "STM", "nome": "Santarém", "aeroporto": "Maestro Wilson Fonseca", "pais": "Brasil"},
    {"codigo": "AUX", "nome": "Araguaína", "aeroporto": "Araguaína", "pais": "Brasil"},
    {"codigo": "CCM", "nome": "Criciúma", "aeroporto": "Diomício Freitas", "pais": "Brasil"},
    {"codigo": "CAC", "nome": "Cascavel", "aeroporto": "Adalberto Mendes da Silva", "pais": "Brasil"},
    {"codigo": "MOC", "nome": "Montes Claros", "aeroporto": "Mário Ribeiro", "pais": "Brasil"},
    {"codigo": "IPN", "nome": "Ipatinga", "aeroporto": "Usiminas", "pais": "Brasil"},
    {"codigo": "JJD", "nome": "Jericoacoara", "aeroporto": "Jericoacoara", "pais": "Brasil"},
    {"codigo": "CAU", "nome": "Caruaru", "aeroporto": "Oscar Laranjeira", "pais": "Brasil"},

    {"codigo": "MCO", "nome": "Orlando", "aeroporto": "Orlando International", "pais": "Estados Unidos"},
    {"codigo": "MIA", "nome": "Miami", "aeroporto": "Miami International", "pais": "Estados Unidos"},
    {"codigo": "FLL", "nome": "Fort Lauderdale", "aeroporto": "Fort Lauderdale-Hollywood", "pais": "Estados Unidos"},
    {"codigo": "JFK", "nome": "Nova York", "aeroporto": "John F. Kennedy", "pais": "Estados Unidos"},
    {"codigo": "EWR", "nome": "Newark", "aeroporto": "Newark Liberty", "pais": "Estados Unidos"},
    {"codigo": "LGA", "nome": "Nova York", "aeroporto": "LaGuardia", "pais": "Estados Unidos"},
    {"codigo": "LAX", "nome": "Los Angeles", "aeroporto": "Los Angeles International", "pais": "Estados Unidos"},
    {"codigo": "SFO", "nome": "São Francisco", "aeroporto": "San Francisco International", "pais": "Estados Unidos"},
    {"codigo": "LAS", "nome": "Las Vegas", "aeroporto": "Harry Reid International", "pais": "Estados Unidos"},
    {"codigo": "ATL", "nome": "Atlanta", "aeroporto": "Hartsfield-Jackson", "pais": "Estados Unidos"},
    {"codigo": "ORD", "nome": "Chicago", "aeroporto": "O'Hare International", "pais": "Estados Unidos"},
    {"codigo": "DFW", "nome": "Dallas", "aeroporto": "Dallas/Fort Worth", "pais": "Estados Unidos"},
    {"codigo": "IAH", "nome": "Houston", "aeroporto": "George Bush Intercontinental", "pais": "Estados Unidos"},
    {"codigo": "PHX", "nome": "Phoenix", "aeroporto": "Sky Harbor", "pais": "Estados Unidos"},
    {"codigo": "SEA", "nome": "Seattle", "aeroporto": "Seattle-Tacoma", "pais": "Estados Unidos"},
    {"codigo": "BOS", "nome": "Boston", "aeroporto": "Logan International", "pais": "Estados Unidos"},
    {"codigo": "DEN", "nome": "Denver", "aeroporto": "Denver International", "pais": "Estados Unidos"},
    {"codigo": "MSP", "nome": "Minneapolis", "aeroporto": "Minneapolis-St Paul", "pais": "Estados Unidos"},
    {"codigo": "DTW", "nome": "Detroit", "aeroporto": "Detroit Metropolitan", "pais": "Estados Unidos"},
    {"codigo": "PHL", "nome": "Filadélfia", "aeroporto": "Philadelphia International", "pais": "Estados Unidos"},
    {"codigo": "CLT", "nome": "Charlotte", "aeroporto": "Charlotte Douglas", "pais": "Estados Unidos"},
    {"codigo": "IAD", "nome": "Washington", "aeroporto": "Dulles International", "pais": "Estados Unidos"},
    {"codigo": "DCA", "nome": "Washington", "aeroporto": "Reagan National", "pais": "Estados Unidos"},
    {"codigo": "SAN", "nome": "San Diego", "aeroporto": "San Diego International", "pais": "Estados Unidos"},
    {"codigo": "TPA", "nome": "Tampa", "aeroporto": "Tampa International", "pais": "Estados Unidos"},
    {"codigo": "PDX", "nome": "Portland", "aeroporto": "Portland International", "pais": "Estados Unidos"},
    {"codigo": "AUS", "nome": "Austin", "aeroporto": "Austin-Bergstrom", "pais": "Estados Unidos"},
    {"codigo": "MSY", "nome": "Nova Orleans", "aeroporto": "Louis Armstrong", "pais": "Estados Unidos"},
    {"codigo": "SLC", "nome": "Salt Lake City", "aeroporto": "Salt Lake City International", "pais": "Estados Unidos"},
    {"codigo": "HNL", "nome": "Honolulu", "aeroporto": "Daniel K. Inouye", "pais": "Estados Unidos"},

    {"codigo": "LIS", "nome": "Lisboa", "aeroporto": "Humberto Delgado", "pais": "Portugal"},
    {"codigo": "OPO", "nome": "Porto", "aeroporto": "Francisco Sá Carneiro", "pais": "Portugal"},
    {"codigo": "FAO", "nome": "Faro", "aeroporto": "Faro", "pais": "Portugal"},
    {"codigo": "FNC", "nome": "Funchal", "aeroporto": "Cristiano Ronaldo", "pais": "Portugal"},
    {"codigo": "PDL", "nome": "Ponta Delgada", "aeroporto": "João Paulo II", "pais": "Portugal"},

    {"codigo": "MAD", "nome": "Madrid", "aeroporto": "Adolfo Suárez Madrid-Barajas", "pais": "Espanha"},
    {"codigo": "BCN", "nome": "Barcelona", "aeroporto": "El Prat", "pais": "Espanha"},
    {"codigo": "AGP", "nome": "Málaga", "aeroporto": "Costa del Sol", "pais": "Espanha"},
    {"codigo": "PMI", "nome": "Palma de Mallorca", "aeroporto": "Palma de Mallorca", "pais": "Espanha"},
    {"codigo": "SVQ", "nome": "Sevilha", "aeroporto": "San Pablo", "pais": "Espanha"},
    {"codigo": "VLC", "nome": "Valência", "aeroporto": "Valencia", "pais": "Espanha"},
    {"codigo": "IBZ", "nome": "Ibiza", "aeroporto": "Ibiza", "pais": "Espanha"},

    {"codigo": "CDG", "nome": "Paris", "aeroporto": "Charles de Gaulle", "pais": "França"},
    {"codigo": "ORY", "nome": "Paris", "aeroporto": "Orly", "pais": "França"},
    {"codigo": "NCE", "nome": "Nice", "aeroporto": "Côte d'Azur", "pais": "França"},
    {"codigo": "LYS", "nome": "Lyon", "aeroporto": "Lyon-Saint Exupéry", "pais": "França"},
    {"codigo": "MRS", "nome": "Marselha", "aeroporto": "Marseille Provence", "pais": "França"},

    {"codigo": "LHR", "nome": "Londres", "aeroporto": "Heathrow", "pais": "Reino Unido"},
    {"codigo": "LGW", "nome": "Londres", "aeroporto": "Gatwick", "pais": "Reino Unido"},
    {"codigo": "STN", "nome": "Londres", "aeroporto": "Stansted", "pais": "Reino Unido"},
    {"codigo": "LTN", "nome": "Londres", "aeroporto": "Luton", "pais": "Reino Unido"},
    {"codigo": "MAN", "nome": "Manchester", "aeroporto": "Manchester", "pais": "Reino Unido"},
    {"codigo": "EDI", "nome": "Edimburgo", "aeroporto": "Edinburgh", "pais": "Reino Unido"},
    {"codigo": "GLA", "nome": "Glasgow", "aeroporto": "Glasgow", "pais": "Reino Unido"},

    {"codigo": "FCO", "nome": "Roma", "aeroporto": "Fiumicino", "pais": "Itália"},
    {"codigo": "MXP", "nome": "Milão", "aeroporto": "Malpensa", "pais": "Itália"},
    {"codigo": "LIN", "nome": "Milão", "aeroporto": "Linate", "pais": "Itália"},
    {"codigo": "VCE", "nome": "Veneza", "aeroporto": "Marco Polo", "pais": "Itália"},
    {"codigo": "NAP", "nome": "Nápoles", "aeroporto": "Capodichino", "pais": "Itália"},
    {"codigo": "FLR", "nome": "Florença", "aeroporto": "Peretola", "pais": "Itália"},
    {"codigo": "BGY", "nome": "Bérgamo", "aeroporto": "Orio al Serio", "pais": "Itália"},
    {"codigo": "CIA", "nome": "Roma", "aeroporto": "Ciampino", "pais": "Itália"},

    {"codigo": "FRA", "nome": "Frankfurt", "aeroporto": "Frankfurt", "pais": "Alemanha"},
    {"codigo": "MUC", "nome": "Munique", "aeroporto": "Franz Josef Strauss", "pais": "Alemanha"},
    {"codigo": "TXL", "nome": "Berlim", "aeroporto": "Tegel", "pais": "Alemanha"},
    {"codigo": "BER", "nome": "Berlim", "aeroporto": "Brandenburg", "pais": "Alemanha"},
    {"codigo": "DUS", "nome": "Düsseldorf", "aeroporto": "Düsseldorf", "pais": "Alemanha"},
    {"codigo": "HAM", "nome": "Hamburgo", "aeroporto": "Hamburg", "pais": "Alemanha"},

    {"codigo": "AMS", "nome": "Amsterdã", "aeroporto": "Schiphol", "pais": "Holanda"},
    {"codigo": "BRU", "nome": "Bruxelas", "aeroporto": "Brussels", "pais": "Bélgica"},
    {"codigo": "ZRH", "nome": "Zurique", "aeroporto": "Zurich", "pais": "Suíça"},
    {"codigo": "GVA", "nome": "Genebra", "aeroporto": "Geneva", "pais": "Suíça"},
    {"codigo": "VIE", "nome": "Viena", "aeroporto": "Vienna International", "pais": "Áustria"},
    {"codigo": "CPH", "nome": "Copenhague", "aeroporto": "Copenhagen", "pais": "Dinamarca"},
    {"codigo": "OSL", "nome": "Oslo", "aeroporto": "Gardermoen", "pais": "Noruega"},
    {"codigo": "ARN", "nome": "Estocolmo", "aeroporto": "Arlanda", "pais": "Suécia"},
    {"codigo": "HEL", "nome": "Helsinque", "aeroporto": "Helsinki-Vantaa", "pais": "Finlândia"},
    {"codigo": "DUB", "nome": "Dublin", "aeroporto": "Dublin", "pais": "Irlanda"},
    {"codigo": "ATH", "nome": "Atenas", "aeroporto": "Eleftherios Venizelos", "pais": "Grécia"},
    {"codigo": "PRG", "nome": "Praga", "aeroporto": "Václav Havel", "pais": "República Tcheca"},
    {"codigo": "BUD", "nome": "Budapeste", "aeroporto": "Ferenc Liszt", "pais": "Hungria"},
    {"codigo": "WAW", "nome": "Varsóvia", "aeroporto": "Chopin", "pais": "Polônia"},
    {"codigo": "OTP", "nome": "Bucareste", "aeroporto": "Henri Coandă", "pais": "Romênia"},
    {"codigo": "IST", "nome": "Istambul", "aeroporto": "Istanbul", "pais": "Turquia"},
    {"codigo": "SAW", "nome": "Istambul", "aeroporto": "Sabiha Gökçen", "pais": "Turquia"},

    {"codigo": "EZE", "nome": "Buenos Aires", "aeroporto": "Ministro Pistarini", "pais": "Argentina"},
    {"codigo": "AEP", "nome": "Buenos Aires", "aeroporto": "Jorge Newbery", "pais": "Argentina"},
    {"codigo": "COR", "nome": "Córdoba", "aeroporto": "Ingeniero Taravella", "pais": "Argentina"},
    {"codigo": "MDZ", "nome": "Mendoza", "aeroporto": "El Plumerillo", "pais": "Argentina"},
    {"codigo": "IGR", "nome": "Iguazú", "aeroporto": "Cataratas del Iguazú", "pais": "Argentina"},
    {"codigo": "USH", "nome": "Ushuaia", "aeroporto": "Malvinas Argentinas", "pais": "Argentina"},
    {"codigo": "BRC", "nome": "Bariloche", "aeroporto": "Teniente Luis Candelaria", "pais": "Argentina"},

    {"codigo": "SCL", "nome": "Santiago", "aeroporto": "Arturo Merino Benítez", "pais": "Chile"},
    {"codigo": "IPC", "nome": "Ilha de Páscoa", "aeroporto": "Mataveri", "pais": "Chile"},
    {"codigo": "ANF", "nome": "Antofagasta", "aeroporto": "Andrés Sabella", "pais": "Chile"},
    {"codigo": "PUQ", "nome": "Punta Arenas", "aeroporto": "Presidente Carlos Ibáñez", "pais": "Chile"},

    {"codigo": "LIM", "nome": "Lima", "aeroporto": "Jorge Chávez", "pais": "Peru"},
    {"codigo": "CUZ", "nome": "Cusco", "aeroporto": "Alejandro Velasco Astete", "pais": "Peru"},
    {"codigo": "AQP", "nome": "Arequipa", "aeroporto": "Rodríguez Ballón", "pais": "Peru"},

    {"codigo": "BOG", "nome": "Bogotá", "aeroporto": "El Dorado", "pais": "Colômbia"},
    {"codigo": "MDE", "nome": "Medellín", "aeroporto": "José María Córdova", "pais": "Colômbia"},
    {"codigo": "CLO", "nome": "Cali", "aeroporto": "Alfonso Bonilla Aragón", "pais": "Colômbia"},
    {"codigo": "CTG", "nome": "Cartagena", "aeroporto": "Rafael Núñez", "pais": "Colômbia"},

    {"codigo": "MEX", "nome": "Cidade do México", "aeroporto": "Benito Juárez", "pais": "México"},
    {"codigo": "CUN", "nome": "Cancún", "aeroporto": "Cancún", "pais": "México"},
    {"codigo": "GDL", "nome": "Guadalajara", "aeroporto": "Miguel Hidalgo", "pais": "México"},
    {"codigo": "MTY", "nome": "Monterrey", "aeroporto": "General Mariano Escobedo", "pais": "México"},
    {"codigo": "TIJ", "nome": "Tijuana", "aeroporto": "General Abelardo L. Rodríguez", "pais": "México"},
    {"codigo": "PVR", "nome": "Puerto Vallarta", "aeroporto": "Gustavo Díaz Ordaz", "pais": "México"},
    {"codigo": "SJD", "nome": "Los Cabos", "aeroporto": "Los Cabos", "pais": "México"},

    {"codigo": "PTY", "nome": "Cidade do Panamá", "aeroporto": "Tocumen", "pais": "Panamá"},
    {"codigo": "UIO", "nome": "Quito", "aeroporto": "Mariscal Sucre", "pais": "Equador"},
    {"codigo": "GYE", "nome": "Guayaquil", "aeroporto": "José Joaquín de Olmedo", "pais": "Equador"},
    {"codigo": "ASU", "nome": "Assunção", "aeroporto": "Silvio Pettirossi", "pais": "Paraguai"},
    {"codigo": "MVD", "nome": "Montevidéu", "aeroporto": "Carrasco", "pais": "Uruguai"},
    {"codigo": "PDP", "nome": "Punta del Este", "aeroporto": "Laguna del Sauce", "pais": "Uruguai"},
    {"codigo": "LPB", "nome": "La Paz", "aeroporto": "El Alto", "pais": "Bolívia"},
    {"codigo": "VVI", "nome": "Santa Cruz", "aeroporto": "Viru Viru", "pais": "Bolívia"},
    {"codigo": "CCS", "nome": "Caracas", "aeroporto": "Simón Bolívar", "pais": "Venezuela"},

    {"codigo": "YYZ", "nome": "Toronto", "aeroporto": "Pearson", "pais": "Canadá"},
    {"codigo": "YVR", "nome": "Vancouver", "aeroporto": "Vancouver International", "pais": "Canadá"},
    {"codigo": "YUL", "nome": "Montreal", "aeroporto": "Pierre Elliott Trudeau", "pais": "Canadá"},
    {"codigo": "YYC", "nome": "Calgary", "aeroporto": "Calgary International", "pais": "Canadá"},

    {"codigo": "DXB", "nome": "Dubai", "aeroporto": "Dubai International", "pais": "Emirados Árabes"},
    {"codigo": "DOH", "nome": "Doha", "aeroporto": "Hamad International", "pais": "Catar"},
    {"codigo": "AUH", "nome": "Abu Dhabi", "aeroporto": "Abu Dhabi International", "pais": "Emirados Árabes"},
    {"codigo": "CAI", "nome": "Cairo", "aeroporto": "Cairo International", "pais": "Egito"},
    {"codigo": "TLV", "nome": "Tel Aviv", "aeroporto": "Ben Gurion", "pais": "Israel"},

    {"codigo": "JNB", "nome": "Joanesburgo", "aeroporto": "OR Tambo", "pais": "África do Sul"},
    {"codigo": "CPT", "nome": "Cidade do Cabo", "aeroporto": "Cape Town International", "pais": "África do Sul"},
    {"codigo": "LOS", "nome": "Lagos", "aeroporto": "Murtala Muhammed", "pais": "Nigéria"},
    {"codigo": "NBO", "nome": "Nairóbi", "aeroporto": "Jomo Kenyatta", "pais": "Quênia"},
    {"codigo": "ADD", "nome": "Adis Abeba", "aeroporto": "Bole", "pais": "Etiópia"},
    {"codigo": "CMN", "nome": "Casablanca", "aeroporto": "Mohammed V", "pais": "Marrocos"},

    {"codigo": "SIN", "nome": "Singapura", "aeroporto": "Changi", "pais": "Singapura"},
    {"codigo": "HKG", "nome": "Hong Kong", "aeroporto": "Hong Kong International", "pais": "China"},
    {"codigo": "PEK", "nome": "Pequim", "aeroporto": "Capital International", "pais": "China"},
    {"codigo": "PVG", "nome": "Xangai", "aeroporto": "Pudong", "pais": "China"},
    {"codigo": "CAN", "nome": "Cantão", "aeroporto": "Baiyun", "pais": "China"},
    {"codigo": "NRT", "nome": "Tóquio", "aeroporto": "Narita", "pais": "Japão"},
    {"codigo": "HND", "nome": "Tóquio", "aeroporto": "Haneda", "pais": "Japão"},
    {"codigo": "KIX", "nome": "Osaka", "aeroporto": "Kansai", "pais": "Japão"},
    {"codigo": "ICN", "nome": "Seul", "aeroporto": "Incheon", "pais": "Coreia do Sul"},
    {"codigo": "BKK", "nome": "Bangkok", "aeroporto": "Suvarnabhumi", "pais": "Tailândia"},
    {"codigo": "KUL", "nome": "Kuala Lumpur", "aeroporto": "Kuala Lumpur International", "pais": "Malásia"},
    {"codigo": "CGK", "nome": "Jacarta", "aeroporto": "Soekarno-Hatta", "pais": "Indonésia"},
    {"codigo": "DPS", "nome": "Bali", "aeroporto": "Ngurah Rai", "pais": "Indonésia"},
    {"codigo": "MNL", "nome": "Manila", "aeroporto": "Ninoy Aquino", "pais": "Filipinas"},
    {"codigo": "HAN", "nome": "Hanói", "aeroporto": "Noi Bai", "pais": "Vietnã"},
    {"codigo": "SGN", "nome": "Ho Chi Minh", "aeroporto": "Tan Son Nhat", "pais": "Vietnã"},
    {"codigo": "BOM", "nome": "Mumbai", "aeroporto": "Chhatrapati Shivaji", "pais": "Índia"},
    {"codigo": "DEL", "nome": "Nova Deli", "aeroporto": "Indira Gandhi", "pais": "Índia"},
    {"codigo": "BLR", "nome": "Bangalore", "aeroporto": "Kempegowda", "pais": "Índia"},

    {"codigo": "SYD", "nome": "Sydney", "aeroporto": "Kingsford Smith", "pais": "Austrália"},
    {"codigo": "MEL", "nome": "Melbourne", "aeroporto": "Tullamarine", "pais": "Austrália"},
    {"codigo": "BNE", "nome": "Brisbane", "aeroporto": "Brisbane", "pais": "Austrália"},
    {"codigo": "PER", "nome": "Perth", "aeroporto": "Perth", "pais": "Austrália"},
    {"codigo": "AKL", "nome": "Auckland", "aeroporto": "Auckland", "pais": "Nova Zelândia"},
    {"codigo": "CHC", "nome": "Christchurch", "aeroporto": "Christchurch", "pais": "Nova Zelândia"},
    {"codigo": "PPT", "nome": "Papeete", "aeroporto": "Faa'a", "pais": "Polinésia Francesa"},
    {"codigo": "NAN", "nome": "Nadi", "aeroporto": "Nadi International", "pais": "Fiji"},

    {"codigo": "YEG", "nome": "Edmonton", "aeroporto": "Edmonton International", "pais": "Canadá"},
    {"codigo": "YWG", "nome": "Winnipeg", "aeroporto": "James Richardson", "pais": "Canadá"},
    {"codigo": "YOW", "nome": "Ottawa", "aeroporto": "Macdonald-Cartier", "pais": "Canadá"},
    {"codigo": "YHZ", "nome": "Halifax", "aeroporto": "Halifax Stanfield", "pais": "Canadá"}
];
